site_name: Radiodan Client Library
theme: readthedocs
pages:
  - ['index.md', 'Home']
  - ['usage/players-playlists.md', 'Usage', 'Players & Playlists']
  - ['usage/audio-devices.md', 'Usage', 'Audio Devices']
  - ['usage/physical-buttons-and-interface.md', 'Usage', 'Physical Buttons & Interface']
  - ['usage/express-middleware.md', 'Usage', 'Express Middleware']
  - ['api/player.md', 'API', 'Player']
